In [37]:

import pandas as pd

df_t = pd.read_parquet("data/processed/historical_3y_to_2025-08-18_ticker.parquet")
df_c = pd.read_parquet("data/processed/historical_3y_to_2025-08-18_column.parquet")
print(df_t[:0])
print(df_c[:0])

Empty DataFrame
Columns: [(AAPL, Open), (AAPL, High), (AAPL, Low), (AAPL, Close), (AAPL, Adj Close), (MSFT, Open), (MSFT, High), (MSFT, Low), (MSFT, Close), (MSFT, Adj Close), (JNJ, Open), (JNJ, High), (JNJ, Low), (JNJ, Close), (JNJ, Adj Close), (JPM, Open), (JPM, High), (JPM, Low), (JPM, Close), (JPM, Adj Close), (XOM, Open), (XOM, High), (XOM, Low), (XOM, Close), (XOM, Adj Close), (AMZN, Open), (AMZN, High), (AMZN, Low), (AMZN, Close), (AMZN, Adj Close), (GOOGL, Open), (GOOGL, High), (GOOGL, Low), (GOOGL, Close), (GOOGL, Adj Close), (TSLA, Open), (TSLA, High), (TSLA, Low), (TSLA, Close), (TSLA, Adj Close), (SPY, Open), (SPY, High), (SPY, Low), (SPY, Close), (SPY, Adj Close), (GLD, Open), (GLD, High), (GLD, Low), (GLD, Close), (GLD, Adj Close), (^GSPC, Open), (^GSPC, High), (^GSPC, Low), (^GSPC, Close), (^GSPC, Adj Close)]
Index: []

[0 rows x 55 columns]
Empty DataFrame
Columns: [(Open, AAPL), (Open, MSFT), (Open, JNJ), (Open, JPM), (Open, XOM), (Open, AMZN), (Open, GOOGL), (Open, TSLA), (Open, SPY), (Open, GLD), (Open, ^GSPC), (High, AAPL), (High, MSFT), (High, JNJ), (High, JPM), (High, XOM), (High, AMZN), (High, GOOGL), (High, TSLA), (High, SPY), (High, GLD), (High, ^GSPC), (Low, AAPL), (Low, MSFT), (Low, JNJ), (Low, JPM), (Low, XOM), (Low, AMZN), (Low, GOOGL), (Low, TSLA), (Low, SPY), (Low, GLD), (Low, ^GSPC), (Close, AAPL), (Close, MSFT), (Close, JNJ), (Close, JPM), (Close, XOM), (Close, AMZN), (Close, GOOGL), (Close, TSLA), (Close, SPY), (Close, GLD), (Close, ^GSPC), (Adj Close, AAPL), (Adj Close, MSFT), (Adj Close, JNJ), (Adj Close, JPM), (Adj Close, XOM), (Adj Close, AMZN), (Adj Close, GOOGL), (Adj Close, TSLA), (Adj Close, SPY), (Adj Close, GLD), (Adj Close, ^GSPC)]
Index: []

[0 rows x 55 columns]

In [44]:
df_c.tail()

Price             Open                                                  \
Ticker            AAPL        MSFT         JNJ         JPM         XOM
Date
2025-08-12  228.009995  523.750000  174.000000  291.500000  106.339996
2025-08-13  231.070007  532.109985  173.000000  293.950012  106.000000
2025-08-14  234.059998  522.559998  174.309998  290.579987  107.550003
2025-08-15  234.000000  522.770020  175.570007  294.839996  106.190002
2025-08-18  231.699997  521.590027  176.500000  290.000000  106.099998

Price                                                                   ...  \
Ticker            AMZN       GOOGL        TSLA         SPY         GLD  ...
Date                                                                    ...
2025-08-12  222.229996  201.369995  345.000000  638.289978  308.220001  ...
2025-08-13  222.000000  204.130005  341.500000  644.909973  309.100006  ...
2025-08-14  227.399994  201.500000  335.760010  642.789978  307.929993  ...
2025-08-15  232.580002  203.850006  337.660004  645.989990  307.339996  ...
2025-08-18  230.229996  204.199997  329.619995  642.859985  307.790009  ...

Price        Adj Close                                                  \
Ticker            MSFT         JNJ         JPM         XOM        AMZN
Date
2025-08-12  529.239990  172.779999  292.850006  105.151520  221.470001
2025-08-13  520.580017  174.419998  290.529999  106.607971  224.559998
2025-08-14  522.479980  174.720001  294.160004  106.389999  230.979996
2025-08-15  520.169983  176.639999  290.489990  106.489998  231.029999
2025-08-18  517.099976  176.250000  291.529999  106.720001  231.490005

Price
Ticker           GOOGL        TSLA         SPY         GLD        ^GSPC
Date
2025-08-12  203.339996  340.839996  642.690002  308.269989  6445.759766
2025-08-13  201.960007  339.380005  644.890015  309.209991  6466.580078
2025-08-14  202.940002  335.579987  644.950012  307.250000  6468.540039
2025-08-15  203.899994  330.559998  643.440002  307.429993  6449.799805
2025-08-18  203.500000  335.160004  643.299988  306.950012  6449.149902

[5 rows x 55 columns]

In [47]:
data = pd.read_parquet("data/raw/intraday/latest_data_tickers.parquet")
data.tail()

Ticker                           AAPL                                      \
Price                            Open        High         Low       Close
Datetime
2025-08-19 18:26:00+00:00  230.154999  230.210007  230.039993  230.112503
2025-08-19 18:27:00+00:00  230.100006  230.130005  229.990005  230.009995
2025-08-19 18:28:00+00:00  230.009995  230.024597  229.919998  229.940002
2025-08-19 18:29:00+00:00  229.949905  230.059998  229.880295  230.050003
2025-08-19 18:30:00+00:00  229.940002  229.940002  229.940002  229.940002

Ticker                                       MSFT                          \
Price                       Adj Close        Open        High         Low
Datetime
2025-08-19 18:26:00+00:00  230.112503  510.709991  510.739990  510.690002
2025-08-19 18:27:00+00:00  230.009995  510.720001  510.720001  510.519989
2025-08-19 18:28:00+00:00  229.940002  510.640015  510.700012  510.630310
2025-08-19 18:29:00+00:00  230.050003  510.649994  510.709991  510.649994
2025-08-19 18:30:00+00:00  229.940002  510.809998  510.809998  510.809998

Ticker                                             ...         GLD  \
Price                           Close   Adj Close  ...        Open
Datetime                                           ...
2025-08-19 18:26:00+00:00  510.739594  510.739594  ...  305.529907
2025-08-19 18:27:00+00:00  510.605011  510.605011  ...  305.529999
2025-08-19 18:28:00+00:00  510.690002  510.690002  ...  305.540009
2025-08-19 18:29:00+00:00  510.700012  510.700012  ...  305.559998
2025-08-19 18:30:00+00:00  510.809998  510.809998  ...  305.562500

Ticker                                                                     \
Price                            High         Low       Close   Adj Close
Datetime
2025-08-19 18:26:00+00:00  305.549103  305.529907  305.529999  305.529999
2025-08-19 18:27:00+00:00  305.540009  305.510010  305.540009  305.540009
2025-08-19 18:28:00+00:00  305.570007  305.540009  305.559998  305.559998
2025-08-19 18:29:00+00:00  305.570007  305.540009  305.565002  305.565002
2025-08-19 18:30:00+00:00  305.562500  305.562500  305.562500  305.562500

Ticker                           ^GSPC                                         \
Price                             Open         High          Low        Close
Datetime
2025-08-19 18:26:00+00:00  6407.669922  6408.250000  6406.750000  6406.790039
2025-08-19 18:27:00+00:00  6406.870117  6406.990234  6404.910156  6405.049805
2025-08-19 18:28:00+00:00  6405.060059  6406.299805  6405.060059  6406.000000
2025-08-19 18:29:00+00:00  6406.009766  6406.160156  6405.520020  6406.160156
2025-08-19 18:30:00+00:00  6405.910156  6405.910156  6405.910156  6405.910156

Ticker
Price                        Adj Close
Datetime
2025-08-19 18:26:00+00:00  6406.790039
2025-08-19 18:27:00+00:00  6405.049805
2025-08-19 18:28:00+00:00  6406.000000
2025-08-19 18:29:00+00:00  6406.160156
2025-08-19 18:30:00+00:00  6405.910156

[5 rows x 55 columns]